### ISSUE TITLE
CSRF token mismatch on redirect from an API endpoint

### ISSUE THREAD

**Issue by OyewoleOyedeji** [Morgbn/nuxt-csurf#10]
In my use case, once a user authorizes my Discord application, the redirect URL (my callback endpoint) redirects, to a `/account` page

But every time upon the redirect the value of csrf in `const { csrf } = useCsrf()` changes (that's what I think keeps causing the CSRF token mismatch)

**Comment by Morgbn** [comment]
The token can change many times, but as long as the secret (stored in a cookie) remains the same, it shouldn't rise "CSRF Token Mismatch", because it's the server key and the secret that allow you to check the validity of the token(s).
If the problem persists, please create a minimal reproduction, it will be easier to help
