### ISSUE TITLE
Allow 'csrf-token' to be read from a form input to allow non-javascript form submit 

### ISSUE THREAD

**Issue by mpowell-atomic** [Morgbn/nuxt-csurf#26]
Hi! Happy new year and thank you for this package! Would you be open to adding a fallback check for the csrf token from a form input value so as to allow csrf on a normal form POST action that doesn't use the fetch methods? I would like to be able to use this package in the use case where there is no javascript. Can make a pull request if this is something that you'd be interested in.

Thank you!

**Comment by Morgbn** [comment]
Hi ! I'm open to PR,
but please make this optional, because "it is more secure to insert the CSRF token in a custom HTTP request header via JavaScript than adding a CSRF token in the hidden field form parameter." ([ref OWASP](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html))
Feel free to re-open this issue if needed

**Comment by mpowell-atomic** [comment]
hello! by optional would you say that it could check the header for the token first and then check the request body for the token if that header token isn't present? e.g. something like this:

```js
const token = getHeader(event, 'csrf-token') ?? requestBody['csrf-token'] ?? '';
```

or have a specific config setting to allow checking for it? cheers!
