### ISSUE TITLE
"403 CSRF Token Mismatch" with prerendered routes

### ISSUE THREAD

**Issue by montythemack** [Morgbn/nuxt-csurf#42]
I get this error after installing the package and submitting a form in nuxt 3. The backend is using Nuxt server components.

403
CSRF Token Mismatch

**Comment by Morgbn** [comment]
Please provide a reproduction link, or at least your configuration and environment. I can't help without it

**Comment by iforgetyounow** [comment]
> Please provide a reproduction link, or at least your configuration and environment. I can't help without it

#43 Same issue

**Comment by bojanrajh** [comment]
@iforgetyounow @montythemack @Morgbn Can you guys check https://github.com/Morgbn/nuxt-csurf/issues/28#issuecomment-2194360017

**Comment by bojanrajh** [comment]
@Morgbn The "Broken examples" are a result of a few `console.log`s to see what's happening in the background because of the silently suppressed error - the root cause of this is fixed by setting `csurf.encryptSecret` in prod env (Vercel, serverless). It worked well in local env, without the secret being set, even on the homepage (see below).

The second issue with this library is that it doesn't support pre-rendered pages with client-side rendering (where the CSRF token is statically rendered there). A workaround for this is to call `routes.clear()` in the `prerender:routes` hook as proposed by Nuxt docs in the rendering section, but this results in a broken Nuxt Content module (because of required pre-rendered json route), so our current *solution* is to call `routes.delete('/')` instead (as `/` is the only entry left in the `routes`, in addition to Nuxt Content's `json`).

**Comment by Morgbn** [comment]
@bojanrajh thanks for your detailed comment !
When you say "pre-rendered pages with client-side rendering" you mean that you have `routeRules: { '*': { prerender: true } }` in your `nuxt.config` ?
If so try adding `'/api/**': { prerender: false }` as mentioned [here](https://github.com/Morgbn/nuxt-csurf/issues/40), to prevent nuxt to pre-render your API routes

**Comment by Morgbn** [comment]
@bojanrajh I tried the `digital-ocean` preset + `ssr: false` on the playground, and launch it locally, but I don't encounter any errors 😥. With this config: 
```ts
export default defineNuxtConfig({
  modules: [...],
  ssr: false,
  nitro: {
    preset: 'digital-ocean'
  },
  routeRules: {
    '/api/nocsrf': {
      csurf: false
    }
  },
  csurf: {
    https: false, // for localhost
    methodsToProtect: ['POST'],
  }
})
```

**Comment by iforgetyounow** [comment]
> ```ts
> digital-ocean
> ```
Modify configuration and solve problems
methodsToProtect: ['GET','POST', 'PUT','DELETE']-->        methodsToProtect: ['POST', 'PUT','DELETE']
cannot configure GET

**Comment by iforgetyounow** [comment]
> @bojanrajh I tried the `digital-ocean` preset + `ssr: false` on the playground, and launch it locally, but I don't encounter any errors 😥. With this config:
> 
> ```ts
> export default defineNuxtConfig({
>   modules: [...],
>   ssr: false,
>   nitro: {
>     preset: 'digital-ocean'
>   },
>   routeRules: {
>     '/api/nocsrf': {
>       csurf: false
>     }
>   },
>   csurf: {
>     https: false, // for localhost
>     methodsToProtect: ['POST'],
>   }
> })
> ```

Modify configuration and solve problems
methodsToProtect: ['GET','POST', 'PUT','DELETE']-->        methodsToProtect: ['POST', 'PUT','DELETE']
cannot configure GET

**Comment by Morgbn** [comment]
@iforgetyounow you can configure GET, but not globally ! GET routes are generally not protected with CSRF protection because **GET** requests are intended to be idempotent and safe, meaning they **should only retrieve data without causing any side effects or modifications on the server**. CSRF attacks typically exploit state-changing operations, which are usually performed through POST, PUT, DELETE, or PATCH requests. Thus, CSRF protection is applied to these methods to prevent unauthorized actions.

**Comment by bojanrajh** [comment]
@Morgbn 
Here's a no-diff reproduction from `main` branch, you don't even need to change the preset.
```
git clone git@github.com:Morgbn/nuxt-csurf.git
cd nuxt-csurf
pnpm i
cd playground
npx nuxi@latest dev
# test, works okay - test without csrf header throws error, test with csrf header is successful
# ctrl + c
npx nuxi@latest build
node .output/server/index.mjs
# test, throws error with and without csrf header, csrf token is always the same (view-source:http://localhost:3000/ in different browsers)
```

Anyways, only homepage is affected by default because it's [prerendered](https://nuxt.com/docs/guide/concepts/rendering#deploying-a-static-client-rendered-app) + the error happens if you start on the homepage, navigate to another page and post the form (because token stays the same, hardcoded).

The issue with `'/api/**': { prerender: false }` (and `routes.clear()`) is that is conflics with Nuxt Content (it prerenders some routes in `/api/_content/query/foo.timestamp.json`) and possible other modules as well. But the idea here is correct: one needs to remove all *standard* routes from prerendering, but keep the one generated programatically (by plugins or modules for example).

I guess another approach to implement CSRF token and avoid all those SSR, pre-rendering and caching issues would be to receive it *on-the-fly*, right before the actual request is made so you can also connect it to the session (which would be also more secure?).

**Comment by Morgbn** [comment]
@bojanrajh yes, I think the real problem is this prerender behavior. The csrf token is added in the html head when nitro renders the page. I don't know how to mitigate that quickly, and I don't have time to investigate more now..
